### ISSUE TITLE
创建Chatbot实例后,有一些疑问

### ISSUE THREAD

**Issue by yaoing** [chatopera/chatopera-py-sdk#3]
我想在服务端使用python sdk做问答转发:
```
from chatopera import Chatbot as chatopera_api
chatbot = chatopera_api(app_id='5f32676e1aba0f001b2cdc5b',app_secret='541bdd60e9589c1d91933ee335c84663')
....

info = request.get_json()
answers = chatbot.command(method='post',path='',payload=jsonify(info['text']))
```
不确定`payload`参数接收的参数类型,有没有相关的实例呢?

**Comment by yaoing** [comment]
目前是这种情况：
```
def getAnswerFromOpera():
    info = request.get_json()
    answers = chatbot.command(method='post',path='',
        payload={
            'fromUserId':info['userid'],
            'textMessage':info['text'],
            # 'timestamp':time.time()
    })
```

```
{
  "answers": {
    "error": "invalid timestamp.", 
    "rc": 1
  }, 
  "code": 200
}

```

**Comment by hailiang-wang** [comment]
请求 多轮对话 的示例程序见：

https://github.com/chatopera/chatopera-py-sdk/blob/5941228ea14207a8f0b308dbb630b216613bb50b/demo.py#L62-L66


如果是 [知识库](https://docs.chatopera.com/products/chatbot-platform/faq.html)，query 改为 "/faq/query"。

Chatbot 类的详细介绍 [文档](https://docs.chatopera.com/products/chatbot-platform/integration.html#chatbot%E7%B1%BB)。

注意，method的方法名是**大写**。

**Comment by hailiang-wang** [comment]
"invalid timestamp." 错误是因为认证的签名算法使用了时间同步，参考[常见问题解决](https://docs.chatopera.com/products/chatbot-platform/integration.html#sdk--%E8%BF%94%E5%9B%9E%E9%94%99%E8%AF%AF-invalid-appid)。

**Comment by yaoing** [comment]
OK,谢谢
